manifest:
  remotes:
    - name: kallistoteles
      url-base: https://github.com/kallistoteles
  projects:
    - name: zmk
      remote: kallistoteles
      revision: main
      import: app/west.yml
  self:
    path: config
